'use strict';
const $=id=>document.getElementById(id);
const dirs=['中心','北','東北','東','東南','南','西南','西','西北'];
const bearings=[null,0,45,90,135,180,225,270,315];
const DB_NAME='rain-guard-db',DB_STORE='kv',BG_TAG='rain-guard-check';
const state={pos:null,watch:null,timer:null,sw:null,lastAlert:localStorage.rainGuardLastAlert||'',radius:+(localStorage.rainGuardRadius||5),threshold:+(localStorage.rainGuardThreshold||.1),lead:+(localStorage.rainGuardLead||60),autoLocate:localStorage.rainGuardAutoLocate!=='0'};
const isIOS=/iphone|ipad|ipod/i.test(navigator.userAgent);
const isStandalone=matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;
const clock=t=>new Intl.DateTimeFormat('zh-TW',{hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(t*1000));
function message(t,error=false){$('msg').textContent=t;$('msg').style.color=error?'#ffaaaa':''}
function setState(id,text,kind='wait'){const el=$(id);el.textContent=text;el.className='state '+kind}
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(DB_STORE))r.result.createObjectStore(DB_STORE)};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function dbSet(key,value){const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction(DB_STORE,'readwrite');tx.objectStore(DB_STORE).put(value,key);tx.oncomplete=()=>{db.close();resolve()};tx.onerror=()=>{db.close();reject(tx.error)}})}
function dest(lat,lon,bearing,km){const R=6371,d=km/R,q=bearing*Math.PI/180,p=lat*Math.PI/180,l=lon*Math.PI/180,p2=Math.asin(Math.sin(p)*Math.cos(d)+Math.cos(p)*Math.sin(d)*Math.cos(q)),l2=l+Math.atan2(Math.sin(q)*Math.sin(d)*Math.cos(p),Math.cos(d)-Math.sin(p)*Math.sin(p2));return{lat:p2*180/Math.PI,lon:((l2*180/Math.PI+540)%360)-180}}
function points(){const p=[{lat:state.pos.latitude,lon:state.pos.longitude}];bearings.slice(1).forEach(b=>p.push(dest(state.pos.latitude,state.pos.longitude,b,state.radius)));return p}
function analyze(d,i){const s=d.minutely_15;if(!s?.time?.length)return{index:i,next:null,data:d};const now=Date.now()/1000-60,j=s.time.findIndex((t,k)=>t>=now&&+(s.precipitation[k]||0)>=state.threshold);if(j<0)return{index:i,next:null,data:d};const next=s.time[j],hour=d.hourly;let probability=null;if(hour?.time?.length){let best=0,diff=Infinity;hour.time.forEach((t,k)=>{const x=Math.abs(t-next);if(x<diff){diff=x;best=k}});probability=hour.precipitation_probability?.[best]??null}return{index:i,direction:dirs[i],next,minutes:Math.max(0,Math.round((next*1000-Date.now())/60000)),mm:+(s.precipitation[j]||0),probability,data:d}}
function renderDots(all,winner){const pos=[[50,50],[50,15],[75,25],[85,50],[75,75],[50,85],[25,75],[15,50],[25,25]];$('samples').innerHTML=pos.map(([x,y],i)=>`<span class="sample${all[i]?.next?' wet':''}${winner?.index===i&&winner.minutes<=state.lead?' urgent':''}" style="left:${x}%;top:${y}%" title="${all[i]?.next?dirs[i]+' '+clock(all[i].next):dirs[i]+' 無雨'}"></span>`).join('')}
function renderTimeline(d){const s=d?.minutely_15;if(!s?.time){$('timeline').textContent='暫無資料';return}const now=Date.now()/1000-60,items=s.time.map((t,i)=>({t,i})).filter(x=>x.t>=now).slice(0,12),max=Math.max(.5,...items.map(x=>+(s.precipitation[x.i]||0)));$('timeline').innerHTML=items.map(x=>{const mm=+(s.precipitation[x.i]||0),h=Math.max(2,Math.round(mm/max*52));return`<div class="slot"><div class="barwrap"><div class="bar" style="height:${h}px;opacity:${mm?1:.18}"></div></div><strong>${clock(x.t)}</strong><span>${mm.toFixed(2)} mm</span></div>`}).join('')}
async function saveBackgroundConfig(){if(!state.pos)return;await dbSet('config',{latitude:state.pos.latitude,longitude:state.pos.longitude,radius:state.radius,threshold:state.threshold,lead:state.lead,updatedAt:Date.now()})}
async function showNotification(title,body,tag='rain-guard'){if(!('Notification'in window)||Notification.permission!=='granted')return false;const reg=state.sw||await navigator.serviceWorker?.ready;if(reg)await reg.showNotification(title,{body,icon:'./icons/rain-guard.svg',badge:'./icons/rain-guard.svg',tag,renotify:true,data:{url:'./'}});else new Notification(title,{body});return true}
async function alertRain(w){if(!w||w.minutes>state.lead||!('Notification'in window)||Notification.permission!=='granted')return;const key=w.next+'-'+w.direction;if(key===state.lastAlert)return;const title=w.minutes?'約 '+w.minutes+' 分鐘後可能下雨':'目前偵測到降雨';const body=w.direction+'方向，預估 '+w.mm.toFixed(2)+' mm / 15 分鐘';await showNotification(title,body);state.lastAlert=key;localStorage.rainGuardLastAlert=key;try{if('setAppBadge'in navigator)await navigator.setAppBadge(1)}catch{}}
async function forecast(silent=false){if(!state.pos)return;silent||message('正在更新降雨預報…');try{const ps=points(),u=new URL('https://api.open-meteo.com/v1/forecast');u.searchParams.set('latitude',ps.map(p=>p.lat.toFixed(5)).join(','));u.searchParams.set('longitude',ps.map(p=>p.lon.toFixed(5)).join(','));u.searchParams.set('minutely_15','precipitation,weather_code');u.searchParams.set('hourly','precipitation_probability');u.searchParams.set('forecast_days','2');u.searchParams.set('timeformat','unixtime');u.searchParams.set('timezone','auto');const r=await fetch(u);if(!r.ok)throw Error('氣象服務回應 '+r.status);const raw=await r.json(),sets=Array.isArray(raw)?raw:[raw],all=sets.map(analyze),rainy=all.filter(x=>x.next).sort((a,b)=>a.next-b.next),w=rainy[0];renderDots(all,w);renderTimeline(all[0]?.data);$('updated').textContent='更新於 '+new Date().toLocaleTimeString('zh-TW',{hour12:false});if(!w){$('dot').className='dot safe';$('headline').textContent='目前範圍內無明顯降雨';$('sub').textContent='目前預報時段尚未達到設定門檻。';$('arrival').textContent=$('direction').textContent=$('rain').textContent=$('prob').textContent='—';try{if('clearAppBadge'in navigator)await navigator.clearAppBadge()}catch{}}else{$('dot').className='dot '+(w.minutes<=state.lead?'danger':'warn');$('headline').textContent=w.minutes<=0?'目前可能正在下雨':`約 ${w.minutes} 分鐘後可能下雨`;$('sub').textContent=`雨勢最早由${w.direction}方向進入 ${state.radius} 公里範圍。`;$('arrival').textContent=clock(w.next);$('direction').textContent=w.direction;$('rain').textContent=w.mm.toFixed(2)+' mm';$('prob').textContent=w.probability==null?'模式雨量':w.probability+'%';await alertRain(w)}await saveBackgroundConfig();silent||message('偵測完成；頁面開啟時每 5 分鐘更新。')}catch(e){$('dot').className='dot danger';$('headline').textContent='預報取得失敗';$('sub').textContent='請檢查網路後再試一次。';message(e.message||'未知錯誤',true)}}
async function got(p){const old=state.pos;state.pos={latitude:p.coords.latitude,longitude:p.coords.longitude};$('position').textContent=`${state.pos.latitude.toFixed(4)}, ${state.pos.longitude.toFixed(4)}（精度約 ${Math.round(p.coords.accuracy)} m）`;setState('locationState','已開啟','on');await saveBackgroundConfig();if(!old||Math.hypot(old.latitude-state.pos.latitude,old.longitude-state.pos.longitude)>.0045)forecast()}
function positionError(e){const m={1:'位置權限被拒絕，請到瀏覽器或系統設定允許定位。',2:'目前無法判定位置，請確認定位服務已開啟。',3:'取得位置逾時，請再試一次。'};message(m[e.code]||'取得位置失敗。',true);$('headline').textContent='無法取得位置';setState('locationState',e.code===1?'已拒絕':'取得失敗','off')}
function start(automatic=false){if(!navigator.geolocation)return positionError({code:2});message(automatic?'正在自動取得位置…':'正在重新取得位置…');if(state.watch!==null)navigator.geolocation.clearWatch(state.watch);state.watch=navigator.geolocation.watchPosition(got,positionError,{enableHighAccuracy:true,maximumAge:60000,timeout:20000});clearInterval(state.timer);state.timer=setInterval(()=>forecast(true),300000);$('start').textContent='重新定位'}
async function registerBackgroundCheck(){if(!state.sw)return'unsupported';try{if('periodicSync'in state.sw){await state.sw.periodicSync.register(BG_TAG,{minInterval:15*60*1000});return'periodic'}if('sync'in state.sw){await state.sw.sync.register(BG_TAG);return'once'}return'unsupported'}catch(e){console.warn(e);return'blocked'}}
function updatePermissionUI(mode){if(!('Notification'in window)){setState('notificationState','不支援','off');setState('backgroundState','不支援','off');return}if(Notification.permission==='granted'){setState('notificationState','已開啟','on');$('notify').textContent='背景通知已授權'}else if(Notification.permission==='denied'){setState('notificationState','已拒絕','off');$('notify').textContent='通知已被封鎖'}else setState('notificationState','尚未授權','wait');if(mode==='periodic')setState('backgroundState','定期檢查已註冊','on');else if(mode==='once')setState('backgroundState','支援單次同步','wait');else if(mode==='blocked')setState('backgroundState','系統未允許','off');else if(isIOS)setState('backgroundState',isStandalone?'需雲端推播':'請先加到主畫面','wait');else setState('backgroundState','前景通知','wait');if(isIOS&&!isStandalone)$('permissionHelp').textContent='iPhone：請先在 Safari 按分享 → 加入主畫面，再從主畫面開啟雨境並按「啟用背景通知」。';else if(isIOS)$('permissionHelp').textContent='iPhone 已以主畫面 App 開啟。真正關閉 App 後仍能收到通知，需要後續接上 Web Push 伺服器；目前會在 App 開啟時通知。';else $('permissionHelp').textContent='支援 Periodic Background Sync 的瀏覽器會以最後已知位置做背景檢查；系統可能延後或限制執行頻率。'}
async function enableNotifications(){if(!('Notification'in window))return message('此瀏覽器不支援通知。',true);if(isIOS&&!isStandalone){updatePermissionUI();return message('iPhone 請先把網站加入主畫面，再從主畫面開啟。',true)}const p=await Notification.requestPermission();if(p!=='granted'){updatePermissionUI();return message('通知權限未開啟；若已拒絕，請到系統設定解除封鎖。',true)}localStorage.rainGuardNotifications='1';await saveBackgroundConfig();const mode=await registerBackgroundCheck();updatePermissionUI(mode);await showNotification('雨境通知已啟用',mode==='periodic'?'已註冊最佳可用的背景降雨檢查。':'頁面開啟時會依設定發出降雨預警。','rain-guard-test');message(mode==='periodic'?'背景檢查已註冊；實際執行頻率由系統決定。':'通知已開啟；此裝置未提供可靠的定期背景同步。')}
async function testNotification(){if(!('Notification'in window)||Notification.permission!=='granted')return enableNotifications();await showNotification('雨境測試通知','通知功能正常。降雨接近設定時間時會再次提醒。','rain-guard-test');message('測試通知已送出。')}
function sync(){state.autoLocate=localStorage.rainGuardAutoLocate!=='0';$('autoLocate').checked=state.autoLocate;$('radius').value=state.radius;$('threshold').value=state.threshold;$('lead').value=state.lead;$('radiusText').textContent=state.radius+' km';$('badge').textContent='半徑 '+state.radius+' km';$('thresholdText').textContent=state.threshold.toFixed(2)+' mm / 15 分鐘';$('leadText').textContent=state.lead+' 分鐘'}
[['radius','radius','rainGuardRadius'],['threshold','threshold','rainGuardThreshold'],['lead','lead','rainGuardLead']].forEach(([id,key,store])=>{$(id).addEventListener('input',e=>{state[key]=+e.target.value;localStorage[store]=state[key];sync()});$(id).addEventListener('change',async()=>{await saveBackgroundConfig();state.pos&&forecast()})});
$('autoLocate').addEventListener('change',e=>{state.autoLocate=e.target.checked;localStorage.rainGuardAutoLocate=state.autoLocate?'1':'0';message(state.autoLocate?'下次開啟會自動定位。':'已關閉自動定位。')});
$('start').onclick=()=>start(false);$('refresh').onclick=()=>forecast();$('refreshSettings').onclick=()=>forecast();$('notify').onclick=enableNotifications;$('testNotify').onclick=testNotification;
document.addEventListener('visibilitychange',async()=>{if(document.visibilityState==='visible'){if(state.autoLocate&&state.watch===null)start(true);else state.pos&&forecast(true)}else{try{await saveBackgroundConfig();if(state.sw&&'sync'in state.sw)await state.sw.sync.register(BG_TAG)}catch{}}});
window.addEventListener('online',()=>state.pos&&forecast(true));
(async function boot(){sync();if('serviceWorker'in navigator){try{state.sw=await navigator.serviceWorker.register('./sw.js').then(()=>navigator.serviceWorker.ready)}catch(e){console.warn(e)}}updatePermissionUI();if('Notification'in window&&Notification.permission==='granted'){const mode=await registerBackgroundCheck();updatePermissionUI(mode)}if(state.autoLocate)setTimeout(()=>start(true),250);else{$('headline').textContent='自動定位已關閉';$('sub').textContent='按「重新定位」開始偵測。';$('position').textContent='等待手動定位'}})();
